BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Schueler ADD
	EintrittJahrgangsstufe nvarchar(10) NULL,
	EintrittAm date NULL,
	EintrittAusSchulnummer int NULL,
	Email nvarchar(256) NULL,
	Notfalltelefonnummer nvarchar(256) NULL
GO
ALTER TABLE dbo.Schueler SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Lehrer SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Klasse ADD
	KlassenleiterId int NULL
GO
ALTER TABLE dbo.Klasse ADD CONSTRAINT
	FK_Klasse_Lehrer FOREIGN KEY
	(
	KlassenleiterId
	) REFERENCES dbo.Lehrer
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Klasse SET (LOCK_ESCALATION = TABLE)
GO
COMMIT